server:
  port: 4111
spring:
  application:
    name: email-service
  datasource:
    url: jdbc:mysql://localhost:3306/emailsDb
    username: root
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
